<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = DB::table('categories')->pluck('id', 'name');

        $bebidas   = $categories['Bebidas'];
        $snacks    = $categories['Snacks'];
        $lacteos   = $categories['Lácteos'];
        $panaderia = $categories['Panadería'];
        $limpieza  = $categories['Limpieza'];
        $abarrotes = $categories['Abarrotes'];

        DB::table('products')->insert([

            // — Bebidas (7) —
            [
                'category_id'     => $bebidas,
                'name'            => 'Coca-Cola 600ml',
                'sku'             => 'BEB-001',
                'barcode'         => '7501055300013',
                'description'     => 'Refresco de cola en botella de 600ml',
                'cost_price'      => 8.00,
                'selling_price'   => 12.00,
                'stock'           => 48,
                'low_stock_alert' => 10,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $bebidas,
                'name'            => 'Pepsi 600ml',
                'sku'             => 'BEB-002',
                'barcode'         => '7501032900028',
                'description'     => 'Refresco de cola Pepsi 600ml',
                'cost_price'      => 7.50,
                'selling_price'   => 11.00,
                'stock'           => 36,
                'low_stock_alert' => 10,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $bebidas,
                'name'            => 'Agua Natural 1L',
                'sku'             => 'BEB-003',
                'barcode'         => '7501234500037',
                'description'     => 'Agua purificada embotellada 1 litro',
                'cost_price'      => 4.00,
                'selling_price'   => 7.00,
                'stock'           => 60,
                'low_stock_alert' => 12,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $bebidas,
                'name'            => 'Jugo de Naranja 1L',
                'sku'             => 'BEB-004',
                'barcode'         => '7501055400046',
                'description'     => 'Jugo de naranja natural sin azúcar 1 litro',
                'cost_price'      => 14.00,
                'selling_price'   => 20.00,
                'stock'           => 24,
                'low_stock_alert' => 6,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $bebidas,
                'name'            => 'Gatorade Limón 500ml',
                'sku'             => 'BEB-005',
                'barcode'         => '7501032900055',
                'description'     => 'Bebida deportiva sabor limón 500ml',
                'cost_price'      => 12.00,
                'selling_price'   => 18.00,
                'stock'           => 30,
                'low_stock_alert' => 8,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $bebidas,
                'name'            => 'Leche Saborizada Chocolate 250ml',
                'sku'             => 'BEB-006',
                'barcode'         => '7501234600064',
                'description'     => 'Leche saborizada sabor chocolate 250ml',
                'cost_price'      => 8.50,
                'selling_price'   => 13.00,
                'stock'           => 20,
                'low_stock_alert' => 5,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $bebidas,
                'name'            => 'Café Listo 250ml',
                'sku'             => 'BEB-007',
                'barcode'         => '7501055500073',
                'description'     => 'Café frío listo para tomar 250ml',
                'cost_price'      => 10.00,
                'selling_price'   => 15.00,
                'stock'           => 18,
                'low_stock_alert' => 5,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // — Snacks (6) —
            [
                'category_id'     => $snacks,
                'name'            => 'Sabritas Original 45g',
                'sku'             => 'SNK-001',
                'barcode'         => '7501011100081',
                'description'     => 'Papas fritas sabor original bolsa 45g',
                'cost_price'      => 8.00,
                'selling_price'   => 13.00,
                'stock'           => 50,
                'low_stock_alert' => 10,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $snacks,
                'name'            => 'Doritos Nacho 65g',
                'sku'             => 'SNK-002',
                'barcode'         => '7501011100098',
                'description'     => 'Tostadas de maíz sabor nacho 65g',
                'cost_price'      => 9.00,
                'selling_price'   => 14.00,
                'stock'           => 40,
                'low_stock_alert' => 10,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $snacks,
                'name'            => 'Galletas Marías 200g',
                'sku'             => 'SNK-003',
                'barcode'         => '7501055200105',
                'description'     => 'Galletas de vainilla clásicas 200g',
                'cost_price'      => 12.00,
                'selling_price'   => 18.00,
                'stock'           => 35,
                'low_stock_alert' => 8,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $snacks,
                'name'            => 'Palomitas Naturales 50g',
                'sku'             => 'SNK-004',
                'barcode'         => '7501234700112',
                'description'     => 'Palomitas de maíz con sal 50g',
                'cost_price'      => 6.00,
                'selling_price'   => 10.00,
                'stock'           => 45,
                'low_stock_alert' => 10,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $snacks,
                'name'            => 'Cacahuates Japoneses 100g',
                'sku'             => 'SNK-005',
                'barcode'         => '7501055200129',
                'description'     => 'Cacahuates con cubierta crujiente 100g',
                'cost_price'      => 10.00,
                'selling_price'   => 16.00,
                'stock'           => 28,
                'low_stock_alert' => 6,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $snacks,
                'name'            => 'Barrita de Avena y Miel',
                'sku'             => 'SNK-006',
                'barcode'         => '7501234700136',
                'description'     => 'Barra de cereal con avena y miel 40g',
                'cost_price'      => 7.00,
                'selling_price'   => 12.00,
                'stock'           => 32,
                'low_stock_alert' => 8,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // — Lácteos (6) —
            [
                'category_id'     => $lacteos,
                'name'            => 'Leche Entera 1L',
                'sku'             => 'LAC-001',
                'barcode'         => '7501234800143',
                'description'     => 'Leche entera pasteurizada 1 litro',
                'cost_price'      => 18.00,
                'selling_price'   => 24.00,
                'stock'           => 30,
                'low_stock_alert' => 8,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $lacteos,
                'name'            => 'Yogur Natural 1kg',
                'sku'             => 'LAC-002',
                'barcode'         => '7501055600150',
                'description'     => 'Yogur natural sin azúcar 1 kilogramo',
                'cost_price'      => 22.00,
                'selling_price'   => 32.00,
                'stock'           => 15,
                'low_stock_alert' => 4,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $lacteos,
                'name'            => 'Queso Manchego 400g',
                'sku'             => 'LAC-003',
                'barcode'         => '7501234800167',
                'description'     => 'Queso manchego rebanado 400g',
                'cost_price'      => 45.00,
                'selling_price'   => 62.00,
                'stock'           => 12,
                'low_stock_alert' => 3,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $lacteos,
                'name'            => 'Crema Ácida 500g',
                'sku'             => 'LAC-004',
                'barcode'         => '7501055600174',
                'description'     => 'Crema ácida para cocinar 500g',
                'cost_price'      => 20.00,
                'selling_price'   => 28.00,
                'stock'           => 20,
                'low_stock_alert' => 5,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $lacteos,
                'name'            => 'Mantequilla 90g',
                'sku'             => 'LAC-005',
                'barcode'         => '7501234800181',
                'description'     => 'Mantequilla con sal en barra 90g',
                'cost_price'      => 16.00,
                'selling_price'   => 22.00,
                'stock'           => 25,
                'low_stock_alert' => 6,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $lacteos,
                'name'            => 'Jocoque Seco 400g',
                'sku'             => 'LAC-006',
                'barcode'         => '7501055600198',
                'description'     => 'Jocoque seco estilo árabe 400g',
                'cost_price'      => 28.00,
                'selling_price'   => 38.00,
                'stock'           => 10,
                'low_stock_alert' => 3,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // — Panadería (5) —
            [
                'category_id'     => $panaderia,
                'name'            => 'Pan de Caja Blanco 680g',
                'sku'             => 'PAN-001',
                'barcode'         => '7501055700205',
                'description'     => 'Pan de caja blanco rebanado 680g',
                'cost_price'      => 28.00,
                'selling_price'   => 38.00,
                'stock'           => 20,
                'low_stock_alert' => 5,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $panaderia,
                'name'            => 'Pan de Caja Integral 680g',
                'sku'             => 'PAN-002',
                'barcode'         => '7501055700212',
                'description'     => 'Pan de caja integral rebanado 680g',
                'cost_price'      => 32.00,
                'selling_price'   => 44.00,
                'stock'           => 15,
                'low_stock_alert' => 4,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $panaderia,
                'name'            => 'Concha de Vainilla',
                'sku'             => 'PAN-003',
                'barcode'         => '7501234900229',
                'description'     => 'Pan dulce de concha con cubierta de vainilla',
                'cost_price'      => 3.50,
                'selling_price'   => 6.00,
                'stock'           => 40,
                'low_stock_alert' => 10,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $panaderia,
                'name'            => 'Cuernito de Mantequilla',
                'sku'             => 'PAN-004',
                'barcode'         => '7501234900236',
                'description'     => 'Pan tipo croissant con mantequilla',
                'cost_price'      => 4.00,
                'selling_price'   => 7.00,
                'stock'           => 30,
                'low_stock_alert' => 8,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $panaderia,
                'name'            => 'Roles de Canela x6',
                'sku'             => 'PAN-005',
                'barcode'         => '7501234900243',
                'description'     => 'Paquete de 6 roles de canela con betún',
                'cost_price'      => 22.00,
                'selling_price'   => 32.00,
                'stock'           => 18,
                'low_stock_alert' => 4,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // — Limpieza (6) —
            [
                'category_id'     => $limpieza,
                'name'            => 'Detergente en Polvo 1kg',
                'sku'             => 'LIM-001',
                'barcode'         => '7501055800250',
                'description'     => 'Detergente en polvo multiusos 1 kilogramo',
                'cost_price'      => 28.00,
                'selling_price'   => 40.00,
                'stock'           => 22,
                'low_stock_alert' => 5,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $limpieza,
                'name'            => 'Cloro Blanqueador 1L',
                'sku'             => 'LIM-002',
                'barcode'         => '7501234000267',
                'description'     => 'Cloro blanqueador desinfectante 1 litro',
                'cost_price'      => 10.00,
                'selling_price'   => 16.00,
                'stock'           => 30,
                'low_stock_alert' => 6,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $limpieza,
                'name'            => 'Jabón de Trastes 500ml',
                'sku'             => 'LIM-003',
                'barcode'         => '7501055800274',
                'description'     => 'Jabón líquido lavatrastes limón 500ml',
                'cost_price'      => 18.00,
                'selling_price'   => 26.00,
                'stock'           => 25,
                'low_stock_alert' => 6,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $limpieza,
                'name'            => 'Suavizante de Ropa 1L',
                'sku'             => 'LIM-004',
                'barcode'         => '7501234000281',
                'description'     => 'Suavizante de telas aroma lavanda 1 litro',
                'cost_price'      => 24.00,
                'selling_price'   => 34.00,
                'stock'           => 18,
                'low_stock_alert' => 4,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $limpieza,
                'name'            => 'Esponja Scotch-Brite',
                'sku'             => 'LIM-005',
                'barcode'         => '7501055800298',
                'description'     => 'Esponja para trastes doble cara',
                'cost_price'      => 8.00,
                'selling_price'   => 13.00,
                'stock'           => 40,
                'low_stock_alert' => 10,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $limpieza,
                'name'            => 'Desinfectante Pino 1L',
                'sku'             => 'LIM-006',
                'barcode'         => '7501234000304',
                'description'     => 'Limpiador desinfectante aroma pino 1 litro',
                'cost_price'      => 14.00,
                'selling_price'   => 20.00,
                'stock'           => 20,
                'low_stock_alert' => 5,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // — Abarrotes (5) —
            [
                'category_id'     => $abarrotes,
                'name'            => 'Arroz Blanco 1kg',
                'sku'             => 'ABA-001',
                'barcode'         => '7501055900311',
                'description'     => 'Arroz blanco de grano largo 1 kilogramo',
                'cost_price'      => 18.00,
                'selling_price'   => 26.00,
                'stock'           => 40,
                'low_stock_alert' => 8,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $abarrotes,
                'name'            => 'Frijol Negro 1kg',
                'sku'             => 'ABA-002',
                'barcode'         => '7501234100328',
                'description'     => 'Frijol negro seco de primera calidad 1kg',
                'cost_price'      => 22.00,
                'selling_price'   => 32.00,
                'stock'           => 35,
                'low_stock_alert' => 8,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $abarrotes,
                'name'            => 'Azúcar Estándar 1kg',
                'sku'             => 'ABA-003',
                'barcode'         => '7501055900335',
                'description'     => 'Azúcar refinada estándar 1 kilogramo',
                'cost_price'      => 20.00,
                'selling_price'   => 28.00,
                'stock'           => 30,
                'low_stock_alert' => 8,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $abarrotes,
                'name'            => 'Aceite Vegetal 1L',
                'sku'             => 'ABA-004',
                'barcode'         => '7501234100342',
                'description'     => 'Aceite vegetal para cocinar 1 litro',
                'cost_price'      => 32.00,
                'selling_price'   => 44.00,
                'stock'           => 25,
                'low_stock_alert' => 6,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'category_id'     => $abarrotes,
                'name'            => 'Sal de Mesa 1kg',
                'sku'             => 'ABA-005',
                'barcode'         => '7501055900359',
                'description'     => 'Sal de mesa yodatada 1 kilogramo',
                'cost_price'      => 8.00,
                'selling_price'   => 13.00,
                'stock'           => 50,
                'low_stock_alert' => 10,
                'unit'            => 'pcs',
                'image'           => null,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
        ]);
    }
}
